.TH timidity.cfg 5 "2004年02月01日" "2.13.0"
.SH 名前
timidity.cfg \- TiMidity++ の設定ファイル
.SH 説明
\fItimidity.cfg\fP は，timidity(1) の実行時の様々な設定を行うための設定
ファイルです。音色データの置き場所，音色自体の設定，その他諸々を設定す
ることができます。
.br
\fITiMidity++\fP は，起動時にコマンドラインオプションを見る前に，
\fItimidity.cfg\fP を探索します。このファイルにアクセスできない場合，ま
たライブラリパスがコマンドラインで \fB\-L\fP オプションによって変更され
ている場合は，すべてのオプションを見た後に，新しいライブラリパスに従っ
てデフォルトファイルを(\fB\-c\fP オプションで別の設定ファイルが指定され
ていないならば)再探索します。
.sp
設定ファイルは，MIDI プログラムのインスツルメントファイルへのマッピング
を定義します。もし，複数のファイルが指定された場合には，後に読み込まれ
た設定によって前の設定が上書きされます。
.sp
設定ファイル中には以下の書式が指定可能です:
.TP
.BI "dir " directory
\fIdirectory\fP を探索パスに加えます。加え方は \fB\-L\fP オプションと同
様です。
.br
TiMidity++ では，アーカイブファイルをパッチセットにすることができます。
.sp
例:
.br
dir /usr/local/share/timidity/inst/foo.zip#
.br
bank 0
.br
0 bar.pat
.br
1 baz.pat
.br
2 zoo.pat
.sp
まず，dir で通常のディレクトリのようにアーカイブファイル(上の例では
/usr/local/share/timidity/inst/foo.zip)を指定します。このとき，アーカイ
ブファイル名の最後に \fB#\fP を付けてください。この \fB#\fP があること
で，アーカイブファイルであることを \fITiMidity++\fP は認識します。こう
しておくと，\fIdir\fP で指定されたアーカイブファイルの中のパッチファイ
ルも読み込み対象になります。上の例では，foo.zip の中にある bar.pat，
baz.pat，zoo.pat が読み込まれます。
.TP
.BI "source " file
他の設定ファイルをその場所に挿入し，続行します。source のネストは 50 段
まで可能です。
.TP
.BI "bank " "[MapID1] number"
これ以降変更するトーンバンクを選択します。この文以後の patch の対応付け
は，指定されたトーンバンクに対して行われます。\fIMapID1\fP に gm2，
sc55，sc88，sc88pro，sc8850，xg，xgsfx64 のいずれかを指定することで，特
定のマップを対象にできます。
.TP
.BI "progbase " number
これ以降，プログラム番号を \fInumber\fP から \fInumber+128\fP で設定・
表示します。例えば，\fBprogbase 1\fP とした場合は，それ以降プログラム番
号は 1 から 128 で設定・表示されます。
.TP
.BI "drumset " "[MapID2] number"
変更するドラムセットを選択します。この文以後の patch の対応付けは，指定
されたドラムセットに対して行われます。\fIMapID2\fP に gm2drum，
sc55drum，sc88drum，sc88prodrum，sc8850drum，xgdrum，xgsfx126 のいずれ
かを指定することで，特定のマップを対象にできます。
.TP
.BI "number " "file [options]"
.br
.ns
.TP
.BI "number %font " "file bank prog [key] [options]"
.br
.ns
.TP
.BI "number %sample " "file [options]"
現在のトーンバンクやドラムセットで，MIDI プログラムナンバー \fInumber\fP
で使用する \fIpatch file\fP を指定します。\fIfile\fP が SoundFont の場
合は，\fBnumber %font\fP の書式で特定の \fIbank\fP，\fIprog\fP，
\fIkey\fP の音色データを取り出します。\fIfile\fP が無圧縮の WAV 形式ま
たは AIFF 形式のサンプルファイルの場合は，\fBnumber %sample\fP の書式で
指定します。\fIoptions\fP は，次のものが使用可能です:
.RS
.TP
\fBamp=\fP\fIamplification\fP
インスツルメントのボリュームを \fIamplification\fP% にします。もし値が
指定されていない場合，インスツルメントが読み込まれる時に自動的に設定さ
れます。
.TP
\fBnote=\fP\fInote\fP
インスツルメントを演奏する時に決まった MIDI ノート(音階)を使用します。
\fInote\fP を \fB0\fP にすると，最初に Note On イベントが発生した時点で
のノートを使用します。パーカッションインスツルメントに対しては，もし設
定ファイルで値が設定されていなければ，\fBpatch\fP ファイルに入っている
値を使用します。
.TP
\fBpan=\fP\fIpanning\fP
インスツルメントのデフォルトのパンニングを設定します。\fIpanning\fP は
\fBleft\fP，\fBright\fP，\fBcenter\fP，あるいは \fB\-100\fP から
\fB100\fP までの整数値を取ることができます。\fB-100\fP が最も左，
\fB100\fP が最も右になります。値が与えられていない場合には，\fBpatch\fP
ファイルに入っている値を使用します。もちろん，MIDI ファイル中のパンニン
グコントロールの方が優先されます。
.TP
\fBtune=\fP\fItuning[,...]\fP
インスツルメントのルート周波数を調整します。\fBtune=1\fP とすれば1半音
上がります。\fItuning\fP には小数が利用可能なので，\fBtune=-0.2\fP など
の微調整も可能です。二つ目以降の引数は，音域別に複数のサンプルデータが
含まれている場合に，それぞれ別の値を指定できます。
.TP
\fBrate=\fP\fIattack:decay:sustain:release1:release2:release3[,...]\fP
インスツルメントの ADSR レートを設定するオプションです。0〜255 の値が指
定できます。サステインレートだけを補正したい場合など，
.br
6 GUS/hrpschrd.pat rate=::60
.br
のような狙い撃ち設定も可能です。また，アタックタイムを速くしたいだけで
あれば，
.br
6 GUS/hrpschrd.pat rate=255
.br
という書き方ができます。二つ目以降の引数は，音域別に複数のサンプルデータが
含まれている場合に，それぞれ別の値を指定できます。
.TP
\fBoffset=\fP\fIattack:decay:sustain:release1:release2:release3[,...]\fP
インスツルメントの ADSR オフセットを設定するオプションです。0〜255 の値
が指定できます。 書式についてはほぼ \fBrate=\fP と同様です。
.TP
\fBtremolo=\fP\fIsweep_increment:control_ratio:depth[,...]\fP
トレモロを設定するオプションです。0〜255 の値が指定できます。
\fBrate=\fP 同様，狙い撃ち設定や不要部分の省略が可能です。
\fIsweep_increment\fP は発音してからトレモロが掛かり始めるまでの時間，
\fIcontrol_ratio\fP は振幅が変化する速さ，\fIdepth\fP は 振幅が変化する
深さです。\fBrate=\fP 同様，複数のサンプルに対する設定が可能です。
.TP
\fBvibrato=\fP\fIsweep_increment:phase_increment:depth[,...]\fP
ビブラートを設定するオプションです。0〜255 の値が指定できます。
\fBrate=\fP 同様，狙い撃ち設定や不要部分の省略が可能です。
\fIsweep_increment\fP は発音してからビブラートが掛かり始めるまでの時間，
\fIphase_increment\fP は周波数が変化する速さ，\fIdepth\fP は 周波数が変
化する深さです。\fBrate=\fP 同様，複数のサンプルに対する設定が可能です。
.TP
\fBsclnote=\fP\fInote[,...]\fP
インスツルメントのスケールチューニングの基準とするノートを設定します。
例えば，\fBsclnote=60\fP とすれば，真ん中のドを中心にスケールチューニン
グが行われます。二つ目以降の引数は，音域別に複数のサンプルデータが含ま
れている場合に，それぞれ別の値を指定できます。
.TP
\fBscltune=\fP\fItune[,...]\fP
インスツルメントのスケールチューニングの度合いを cent 単位で設定します。
例えば，\fBscltune=50\fP とすれば，ノート間隔が 50 cent になります。二
つ目以降の引数は，音域別に複数のサンプルデータが含まれている場合に，そ
れぞれ別の値を指定できます。
.TP
\fBmodrate=\fP\fIattack:decay:sustain:release1:release2:release3[,...]\fP
.br
.ns
.TP
\fBmodoffset=\fP\fIattack:decay:sustain:release1:release2:release3[,...]\fP
モジュレーション・エンベロープの変化の仕方を設定します。設定方法や値は，
基本的にボリューム・エンベロープと同じです。一部の SoundFont を除けば，
このオプションだけを指定しても何も起こりません。
.TP
\fBtrempitch=\fP\fInum[,...]\fP
トレモロに従って，ピッチを変化させる深度を設定します。効果そのものはビ
ブラートと一緒ですが，別系統で動作させたいときに利用します。単位は
+-cent です。\fBrate=\fP と同様，複数のサンプルに対する設定が可能です。
\fBtremfc=\fP\fInum[,...]\fP
トレモロに従って，フィルタ・カットオフ周波数を変化させる深度を設定しま
す。いわゆる「グロウル効果」を表現できます。単位その他は trempitch と同
一です。
.TP
\fBmodpitch=\fP\fInum[,...]\fP
モジュレーション・エンベロープに従って，ピッチを変化させる深度を設定し
ます。アタック時だけ一時的に音程が上がるなどの表現が可能です。単位その
他は trempitch と同一です。
.TP
\fBmodfc=\fP\fInum[,...]\fP
モジュレーション・エンベロープに従って，フィルタ・カットオフ周波数を変
化させる深度を設定します。単位その他は trempitch と同一です。
.TP
\fBfc=\fP\fInum[,...]\fP
フィルタ・カットオフ周波数の基準値を設定します。単位は Hz です。
\fBrate=\fP と同様，複数のサンプルに対する設定が可能です。
.TP
\fBq=\fP\fInum[,...]\fP
フィルターの Q(レゾナンス)を設定します。単位は cB です。\fBrate=\fP と
同様，複数のサンプルに対する設定が可能です。
.TP
\fBfckeyf=\fP\fInum\fP
フィルタ・キーフォローを設定します。note=60 を基準として，note に従いカ
ットオフ周波数を変化させます。単位は +-cent/key で，例えば 100 を指定す
れば音程と同じだけ変化します。
.TP
\fBfcvelf=\fP\fInum\fP
フィルタ・ベロシティフォローを設定します。velocity=127 を基準として，
velocity に従いカットオフ周波数を変化させます。単位は +-cent で，
SoundFont では -2400 が固有値として設定されています。
.TP
\fBqvelf=\fP\fInum\fP
レゾナンス・ベロシティフォローを設定します。velocity=0 を基準として，
velocity に従いレゾナンスを変化させます。単位は +-cB です。
.TP
\fBkeep=\fP{\fBloop\fP|\fBenv\fP}
パーカッションインスツルメントでは，デフォルトでループ情報とエンベロー
プ情報が破棄されます。また，メロディーインスツルメントに異常なエンベロ
ープが存在した場合にも，エンベロープ情報は自動的に破棄されます。
\fBkeep\fP を指定することで，エンベロープ情報やループ情報が破棄されるの
を防ぎます。例えば，Short，Long Whistle パーカッションインスツルメント
(General MIDI の 71，72 番)に対しては，設定ファイルで
``\fBkeep=loop keep=env\fP'' としておく必要があります。
.TP
\fBstrip=\fP{\fBloop\fP|\fBenv\fP|\fBtail\fP}
インスツルメントとして使用する \fIpatch\fP の，ループ情報やエンベロープ
情報やテール(ループの後にあるデータ)をすべて強制的に破棄します。サード
パーティーのインスツルメントには，ループの後にゴミが付いているものがあ
り，インスツルメントを演奏する度にクリッキングノイズが入ってしまうこと
があります。その場合，\fBstrip=tail\fP オプションを指定すれば音質が改善
されます。
.TP
\fBcomm=\fP\fIcomment\fP
\fIcomment\fP が指定できます。#extension comm と同じ効果です。
.RE
.TP
.BI "default " file
他のどこにも設定がないような音に出合った場合，このファイルが代理として
発音されます。
.TP
.BI "map " "MapID1 from-bank from-prog to-bank to-prog"
GS/XG 各マップのトーン音色として既存のトーン音色を割り当てます。
\fIMapID1\fP には，\fBgm2\fP, \fBsc55\fP，\fBsc88\fP，\fBsc88pro\fP，
\fBsc8850\fP，\fBxg\fP，\fBxgsfx64\fP が指定できます。
.TP
.BI "map " "MapID2 from-drumset from-keynote to-drumset to-keynote"
GS/XG 各マップのドラム音色として既存のドラム音色を割り当てます。
\fIMapID2\fP には，\fBgm2drum\fP, \fBsc55drum\fP，\fBsc88drum\fP，
\fBsc88prodrum\fP，\fBsc8850drum\fP，\fBxgdrum\fP，\fBxgsfx126\fP が指
定できます。
.TP
.BI "soundfont " "file [options]"
SoundFont を最初から最後まで読み込みます(部分的に読み込むには，
\fBnumber\fP で \fI%font\fP を使います)。\fIoptions\fP は，次のものが使
用可能です:
.RS
.TP
\fBorder=\fP\fInumber\fP
音色データを探す順番を設定します。\fBorder=0\fP のときは，まず
SoundFont を読み込んで，その後に足りないサンプルを GUS/patch から探しま
す。\fBorder=1\fP のときは，GUS/patch を読み込んだ後に SoundFont を読み
込みます。
.TP
\fBamp=\fP\fIamplification\fP
SoundFont 全体の音量を \fIamplification\fP% にします。もし値が指定され
ていない場合，100% に設定されます。
.TP
\fBcutoff=\fP\fInumber\fP
SoundFont に設定された LPF の有効(1)/無効(0)を指定します。もし値が指定
されていない場合，有効となります。
.TP
\fBreso=\fP\fInumber\fP
SoundFont に設定されたレゾナンスの有効(1)/無効(0)を指定します。もし値が
指定されていない場合，有効となります。
.TP
\fBremove\fP
対象の SoundFont を逆にメモリ上から廃棄します。
.RE
.TP
.BI "font exclude " "bank [prog [key]]"
SoundFont の検索を，\fIbank\fP 上の \fIprog\fP で行わないように指定しま
す。ドラムの場合はバンクが 128 でドラムセットが \fIprog\fP，キー番号が
\fIkey\fP になります。
.TP
.BI "font order " "number bank [prog [key]]"
SoundFont の検索順序(上記参照)を，個別に指定するためのものです。引数の
意味は \fBfont exclude\fP と同じです。
.LP
.P
TiMidity++ では，以下の拡張命令が追加されています:
.TP
.BI "#extension altassign " "program1 program2 ..."
ドラムセットについて，オルタネートアサインを設定します。
.sp
drumset 0
.br
altassign 42 44 46
.sp
と書くと，ドラムセット 0 の 42/44/46 が排他的に鳴ります。ドラムセット
0 で定義されたオルタネートアサインはデフォルトで使用されます。
.TP
.BI "#extension comm " "program comment"
Instrument 番号 \fIprogram\fP にコメント \fIcomment\fP を指定します。こ
こで設定した \fIcomment\fP は，\fB\-int\fP や \fI\-iTt\fP オプションで
起動した時に，インジケータラインに表示されます。
.TP
.BI "#extension timeout " "program secound"
Instrument 番号 \fIprogram\fP で，\fIsecound\fP 秒以上 Suspend 状態が続
いた場合，その音をオフにします。
.TP
.BI "#extension copydrumset " drumset
\fIdrumset\fP 番号の状態すべてを，現在の \fIdrumset\fP にコピーします。
.TP
.BI "#extension copybank " bank
\fIbank\fP 番号の状態すべてを，現在の \fIbank\fP にコピーします。
.TP
.BI "#extension copymap " "to-MapID from-MapID"
マップ \fIfrom-MapID\fP に定義されたバンクの状態すべてを，マップ
\fIto-MapID\fP にコピーします。
.TP
.BI "#extension HTTPproxy " hostname:port
HTTP の proxy を設定します。proxy のホスト名を \fIhostname\fP に，ポー
ト番号を \fIport\fP に指定します。
.TP
.BI "#extension FTPproxy " hostname:port
FTP の proxy を設定します。proxy のホスト名を \fIhostname\fP に，ポート
番号を \fIport\fP に指定します。
.TP
.BI "#extension mailaddr " your\-mail\-address
ユーザのメールアドレスを，\fIyour\-mail\-address\fP に指定します。この
メールアドレスは，FTP 接続を proxy を介さずにダイレクトに繋ぐ場合に用い
られます。
.TP
.BI "#extension opt [\-]{option} " [optarg]
起動時のオプションを指定します。
.TP
.BI "#extension undef " progno
現在のバンクのプログラム番号 \fIprogno\fP を未定義にします。
.TP
.BI "#extension legato " "progno {0|1}"
\fIprogno\fP でレガートを掛ける(1)，掛けない(0)を指定します。
.TP
.BI "#extension level " "progno tva_level"
NRPN の Drum Instrument TVA Level を処理する際，音量を変化させる基準と
なる値を設定します。曲中で Drum Instrument TVA Level が指定されない限り，
音量には一切影響しません。あくまで基準値です。
.TP
.BI "#extension redamper " "progno {0|1}"
\fIprogno\fP でリダンパー効果を掛ける(1)，掛けない(0)を指定します。
.TP
.BI "#extension playnote " "progno note"
ドラムセット音色の出音周波数を note とします。GS SysEx Play Note で出音
周波数が指定された場合に，この設定値を元にピッチを適切に変化させます。
\fIprogno\fP は "," や [start]-[end] で一括指定できます。start，end は
省略すると，それぞれ 0，127 と見なされます。
.sp
例:
.br
drumset 0
.br
#extension playnote -37,39,44-46,55-60
.TP
.BI "#extension delaysend " "progno level"
.br
.ns
.TP
.BI "#extension chorussend " "progno level"
.br
.ns
.TP
.BI "#extension reverbsend " "progno level"
ドラムパート・エフェクトがオンの場合のセンドレベルを設定します。初期値
はすべて 127 ですが，delay，chorus，reverb のどれか一つでも設定されてい
れば，その音色に設定されていないエフェクトは初期値 0 になります。
\fIprogno\fP は "," や [start]-[end] で一括指定できます。start，end は
省略すると，それぞれ 0，127 と見なされます。
.TP
.BI "#extension rnddelay " "progno msec"
最大 \fImsec\fP 以内のディレイを，発音毎にランダムで付加します。ランダ
ム値の分布はホワイトノイズというより，むしろピンクノイズ(1/f ゆらぎ)です。
.P
これらの拡張命令は \fB#\fP から始まっており，古い \fITiMidity++\fP では
単なるコメントと扱われ無視されます。よって，古い \fITiMidity\fP との互
換性を保つことができます。
.br
なお，TiMidity++ では #extension は空白として扱われるようになっています。
.P
\fITiMidity++\fP の設定ファイル(*.cfg)中の source の引数に UNIX のコマ
ンドからの出力を利用できます(UNIX のみ)。ファイル名の最後に '|' (ASCII
0x7c)を記述すると UNIX コマンドとみなされ，そのコマンドの出力が source
の引数になります。
.br
\fBsource\fP \fIcommand|\fP のようにすると，\fIcommand\fP の出力が
\fBsource\fP の引数になります。環境によって \fITiMidity++\fP の設定を選
択したい場合などに便利です。なお，\fIcommand\fP \fI|\fP のように，途中
にスペースが入ると，設定ファイル読み込み時に区切られてしまい，コマンド
と見なされなくなってしまいます。この機能はファイル名を指定できるすべて
の場所に適用できます。
.P
.RS
timidity 'cat fild.mid|'
.RE
.P
は，cat fild.mid の出力結果から読み取ります。
.SH ファイル
.TP
.B /etc/timidity.cfg
.TP
.B /usr/local/share/timidity/timidity.cfg
.SH 関連項目
timidity(1), lsmidiprog(1), mididump(1), patinfo(1), sf2text(1), wav2pat(1)
.SH 著作権
Copyright (C) 1999-2004 Masanao Izumo <iz@onicos.co.jp>
.br
Copyright (C) 1995 Tuukka Toivonen <tt@cgs.fi>
.LP
The original version was developed by Tuukka Toivonen <tt@cgs.fi>
until the release of TiMidity-0.2i.  His development was discontinued
because of his being busy with work.
.LP
This program is free software; you can redistribute it and/or modify
it under the terms of the \fIGNU General Public License\fP as
published by the Free Software Foundation; either version 2 of the
License, or (at your option) any later version.
.LP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the \fIGNU
General Public License\fP for more details.
.LP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
USA
.SH 入手元
The latest release is available on the TiMidity++ Page,
.br
URL http://www.timidity.jp/
