.TH TiMidity++ 1 "Jan 06 1999" "1.0.0"
.SH NAME
TiMidity++ \- MIDI to WAVE converter and player
.P
.SH SYNOPSIS
.B timidity
[\-options] filename [filenames ...]
.P
.SH DESCRIPTION
\fITiMidity++\fP は、標準MIDIファイル (*.MID)、
RCPファイル (*.RCP, *.R36, *.G18, *.G36) あるいは
Moduleファイル (*.mod) を、RIFF WAVE 形式等のオーディオファイルへ
コンバートするコンバータです。
各種 MIDI ファイル からデジタルオーディオデータを生成するために、
Gravis Ulstarsound\-互換 の patch ファイル、あるいは AWE32/64 の
sfx、sf2 ファイル などを使用します。
TiMidity++ によって生成されたデータは、更に加工するためにファイルに格納したり、
オーディオデバイスを使ってリアルタイムに演奏したりすることができます。
.br
リアルタイム演奏時には、KARファイル や WRDファイル などを読み込んで、
歌詞を表示する事も出来ます。


.P
.SH FILENAME
ファイルネームには、以下の表記が使用可能です:
.TP
.B \-
標準入力から読み込んだ MIDI ファイルを演奏します。
.TP
.B path/filename
ディスク上のファイルを演奏します。
.TP
.BI dir: "directory"
.br
.ns
.TP
.B directory/
\fIdirectory\fP 内全てのファイルを演奏します。
たとえば、
.br

\fB% timidity some/where/\fP

として起動すると，\fIsome/where/\fP ディレクトリ内全てのファイルが演奏されます。

.TP
.B Archive File
アーカイブファイルから MIDI ファイルを展開しながら演奏します。
アーカイブファイル中の個々のファイルを指定するには、アーカイブファイル名の
後に続けて \fI#\fP を記述し、その後に続けてアーカイブ中のファイル名を指定します。
\fI#\fP の後は UNIX shell の\fI正規表現\fPのパターンに
なっています。ただし、UNIX shell の\fI正規表現\fPとは少し異なり、大文字／小文字
は区別されません。
.br
ここで、\fB\\xHH\fP という表現は、16進数 \fBHH\fP で表したASCII文字列にマッチします。

.RS
例：
.TP
.BI timidity " 'file.zip#file.mid'"
file.zip 中の file.mid ファイルを演奏します。
.TP
.BI timidity " 'file.lzh#*.mid'"
file.lzh 中の *.mid にマッチするファイルを演奏します。
.TP
.BI timidity " 'file.tgz#*'"
これは \fBtimidity 'file.tgz'\fP と等価です。
.PP
これらは自前で展開していますので、Windows
でもこれらのファイルが読めると思います(未確認)。
.PP
\fITiMidity\fPが内部で展開できるアーカイブ形式は以下の通り:
.RS
.TP
.B tar ファイル (*.tar)
.TP
.B tar + gzip'ed ファイル (*.tar.gz, *.tgz)
.TP
.B zip ファイル (*.zip)
.TP
.B lzh ファイル (*.lzh *.lha)
(lh0, lh1, lh2, lh3, lh4, lh5, lh6, lzs, lz5, lz4 対応)
.RE
.PP
なお、これ以外でも、拡張子に対してその展開コマンドがコンパイル時に
定義されている場合、
\fITiMidity\fP は指定された展開コマンドにファイルをパイプで流しこみ、展開します。
.RE

.TP
.B news://news\-server[:port]/Message\-ID
.br
.ns
.TP
.B news://news\-server[:port]/newsgroup[/first\-last]
news-server に保存されている MIDI ファイルを演奏します。
newsgroup を指定すると、そのグループに投稿されている MIDI ファイルを
演奏します。
.br
news://* で指定したファイルは \fBMIME\fP の Multi Part を認識し、そこに
投稿されている MIDI ファイルを展開して演奏することができます。また
通常のファイルであっても、*.mime という拡張子で保存するか、
あるいはファイル名に mime: というプレフィックスを指定して入力すると
MIME を認識します。
現在以下のフォーマットが認識できます:

.RS
.TP
.B uu\-encoded file
\fIbegin\fP という文字から始まっている行が必要
.TP
.B base64 encoded
\fIContent\-Transfer\-Encoding: base64\fP が必要
.TP
.B quoted\-string
\fIContent\-Transfer\-Encoding: quoted\-string\fP が必要
.TP
.B Mac BinHex format
\fIHQX\fP のみ対応
.RE
.TP
.B http://address
.br
.ns
.TP
.B ftp://address
URL で指定した MIDI ファイルを演奏します。
.br
\fBtimidity http://www.goice.co.jp/member/mo/dist/midi/impromptu.mid\fP
.br
のように、ネットワークを介して MIDI ファイルを演奏できます。
同様に、*.cfg ファイル内で URL を指定すればリモートのパッチファイルを
利用することもできます。

.P
.SH INPUT FILE
\fITiMidity\fP が自分で認識し、演奏することができる MIDI ファイルの形式は以下の通りです:
.TP
.B Standard MIDI File ( Format 0, 1, 2 )
.TP
.B .RCP .R36 .G18 .G36 ( カモンミュージック社製レコンポーザ形式 ）
Windows 版では、\fIrcpcv.dll\fP を用いてコンバートを行います。
.TP
.B .KAR ( Karaoke フォーマット )
Lyric Meta Event と同じように、歌詞が表示されます．
.TP
.B .MOD MOD.* (module file)
.TP
.B .WRD ( WRD形式 ）

.P
.SH OPTIONS
\fITiMidity++\fP では次のコマンドラインオプションが使用可能です:

.TP
.BI \-A "amplification"
音量を \fIamplification\fP% にします。デフォルトでは \fB70\fP です。
大きな値を指定するほど大きな音になります。\fB0\fP(無音) から \fB800\fP までの値が有効です。

.TP
.B \-a
アンチエイリアシングを有効にします。
\fB\-s\fPオプションで低いサンプリングレートを指定したときに、折り返し雑音と呼ばれる
不自然な成分が発生することがあります。\fB\-a\fP オプションで起動することで、この
不自然な成分を取り除くことができます。

.TP
.BI \-B "fragments"
音源にデータを書き込む時の分割数を指定します。\fB0\fP から \fB1000\fP までの値が有効です。
フラグメントの数を大きくすると、プロセスが多数動いている時の音切れが減りますが、
早送り、巻き戻し、ボリューム制御などに対する反応は遲くなります。
また、状態表示も同期が取れなくなります。
\fIfragments\fP を 0 にすると、できるだけ大きなフラグメントの値を取ります。
このオプションは Linux、FreeBSD、Windows のみで有効です。

.TP
.BI \-b "mode"
イヤホンで聞いた時の音の臨場感を出すようにします。
\fImode\fPには、以下のモードが有効です:
.RS
.TP
.B \-bl
主に左から音が聞こえてきます。
.TP
.B \-br
主に右から音が聞こえてきます。
.TP
.B \-bb
ときどき、左右の音場が変化します．
.TP
.B \-bc
この機能は無効になります．
.RE

.TP
.BI \-C " ratio"
制御レートを指定します。TiMidity では、
エンベロープやトレモロなどの音量計算を 1 サンプル毎行うのではなく、
複数のサンプルをまとめて計算することで高速化をはかっています。
すなわち、\fIratio\fP サンプル毎に、エンベロープやトレモロの音量が再計算されています。
\fIratio\fP の値を小さくすればするほど音質が良くなりますが、その分 CPU パワー
を必要とします。\fIratio\fP には \fB1\fP〜\fB255\fP までの値を指定することができます。
デフォルトでは 1 msec に相当するサンプル数となっています。

.TP
.BI \-c " filename"
TiMidity の設定ファイル \fIfilename\fPを読み込みます。
TiMidity のデフォルトの設定ファイルを読み込んだ後、
\fIfilename\fP が読み込まれます。

.TP
.BI \-D " channel"
\fIchannel\fP チャネル目をドラムチャネルにします。
\fB\-D\-n\fPのように指定すると、 n チャネル目をドラムではなくメロディチャネルに
することできます。
\fIchannl\fP に \fB0\fP を与えると、全てのチャンネルがメロディチャネルになります。

.TP
.BI \-d " dir"
ダイナミックリンクインターフェースモジュールがインストールされている
ディレクトリを \fIdir\fP で指定します。

.TP
.B \-e
TiMidity のプライオリティをあげます。Windows のみで有効です。
このオプションを有効にすると、TiMidity 以外のプログラムがほとんど動作
出来なくなります。

.TP
.BI \-E " mode"
TiMidity の拡張モードを指定します(複数指定可)。
以下の \fImode\fP が指定できます。:
.RS
.TP
.B w
モジュレーションコントロールを有効にします。
.TP
.B W
モジュレーションコントロールを無効にします。
.TP
.B p
ポルタメントコントロールを有効にします。
.TP
.B P
ポルタメントコントロールを無効にします。
.TP
.B v
NRPN ビブラートを有効にします。
.TP
.B V
NRPN ビブラートを無効にします。
.TP
.B r
リバーブエフェクトコントロールを有効にします。
.TP
.B R
リバーブエフェクトコントロールを無効にします。
.TP
.B c
コーラスエフェクトコントロールを有効にします。
.TP
.BI c " n"
全てのチャネルのコーラスエフェクトを \fIn\fP で演奏します。
.TP
.B C
コーラスフェクトコントロールを無効にします。
.TP
.B s
チャンネルプレッシャーを有効にします。
.TP
.B S
チャンネルプレッシャーを無効にします。
.TP
.B t
全てのテキストメタイベントをトレースします。
.TP
.B T
特定のテキストメタイベントをトレースします。
.TP
.B o
同一音の重複を許します。
.TP
.B O
同一音の重複は許しません。前の音は消音されます。
.TP
.BI m " HH"
マニュファクチュア ID を 2 桁の16数 \fIHH\fP で指定します。
.br
このとき、\fIHH\fP を \fBgm\fP , \fBGM\fP ,\fBGS\fP , \fBGS\fP , \fBxg\fP ,
\fBXG\fP にすることで、それぞれ \fB41\fP, \fB43\fP, \fB7e\fP を指定した
事になります。
.br
入力ファイルから音源を自動的に認識できないような場合には、
このパラメータで強制的に認識させる事が出来ます。
.TP
.BI B " n"
全てのチャネルのパッチのバンクを常に \fIn\fP にします。\fIn\fP を省略すると
デフォルトの動作になります。
.TP
.BI b " n"
パッチのデフォルトのバンクを指定します。\fI\-EBn\fP と異なり、MIDI の
\fBBank select\fP によりバンクが変更されます。
.RE

.TP
.B \-F
このオプションを指定すると、Note ON のままの状態で
Midi control change 10: Panning が有効になります。
デフォルトではすぐには変化しないで、音量の再計算が必要になったときに
変化します。改良版ではトグルオプションになっています。

.TP
.B \-f
このオプションを有効にすると、エンベロープの変化時間が半分になり高速に動作します。
ただし、音の立ち上がりとリリース時間が短くなってしまいます。

.TP
.BI \-g " sec"
Sound-Spectrogram を表示する Window を開きます。
このオプションは \fIX Window System\fP がサポートされている環境のみで動作します。
Sound-Spectrogram は声紋のようなもので、スペクトラムの時間変化を表現したものです。

.TP
.B \-h
この説明を表示します。

.TP
.BI \-I " voice" [/c]
デフォルトのプログラム番号を \fIvoice\fP にします。
デフォルトでは \fIvoice\fP = 0 (通常はピアノ) となっています。
.br
また、\fIvoice\fP の後に \fI/c\fP を付けると、チャネル \fIc\fP の
デフォルトのプログラム番号を指定することが出来ます。\fI/c\fP を
省略した場合には、全チャネルに対する指定となります。

.TP
.BI \-i " mode"
ユーザインターフェースを指定します。
環境によって利用可能なインターフェースが異なります。
以下の \fImode\fP が存在します。:
.RS
.TP
.B \-id
dumb interface
.TP
.B \-in
ncurses interface
.TP
.B \-is
slang interface
.TP
.B \-ia
X Athena Widget interface
.TP
.B \-ik
Tcl/Tk interface
.TP
.B \-im
motif interface
.TP
.B \-iT
vt100 interface
.TP
.B \-ie
Emacs interface (\fIEmacs\fP 上から \fBM\-x timidity\fP により起動されます)
.TP
.B \-ii
skin interface
.br
環境変数 TIMIDITY_SKIN に、使用する skin のパス(圧縮状態でもよい)を
指定しておいてください。
.PP
上記オプションに続けて、以下の文字列を追加することができます(複数指定化)。:
.TP
.B v
冗長表示のレベルを上げます。
.TP
.B q
冗長表示のレベルを下げます。
.TP
.B t
トレース表示の on/off (トグル)。
.RE

.TP
.B \-j
このオプションを有効にすると、演奏しながらパッチファイルを読み込みます。

.TP
.BI \-L " dir"
サーチパスに \fIdir\fP を追加します。
patch ファイル、設定ファイル、MIDI ファイルなどは、
このサーチパスに従って探索されます。
最後に加えられたディレクトリは最初に探索されます。
但し、このサーチパスに関係なく、
カレントディレクトリがいつも最初に探索されるので注意すること。

.TP
.BI \-n " degree"
Noise Shaping Filter を使用します。Noise Shaping Filter により
8 bit linear 出力時の decay での歪みが改善されます。が、
ノイズが高域にシフトし聴感上のノイズも増えます。
.br
\fIdegree\fP には \fB0\fP から \fB4\fP までの値が指定できます。
\fB0\fP のときフィルタは機能せず、\fB4\fPのとき最大の効き方となります。

.TP
.BI \-O " mode"
出力モードやフォーマットを指定します。
以下の \fImode\fP が有効です。:
.RS
.TP
.B \-Od
オーディオデバイスに出力します(デフォルト)。
.TP
.B \-Ow
Windows WAV ファイルを出力します。
.TP
.B \-Or
ヘッダのないオーディオのデータ部分のみを出力します。
.TP
.B \-Ou
Sun Audio (au) ファイルを出力します。
.TP
.B \-Oa
AIFF ファイルを出力します。
.PP
上記オプションに続けて、以下の文字を追加することで出力フォーマットを
指定できます(複数可)。
.TP
.B 8
8\-bit サンプル精度
.TP
.B 1
16\-bit サンプル精度
.TP
.B U
U\-Law 符合化方式
.TP
.B A
A\-Law 符合化方式
.TP
.B l
linear PCM 符合化方式
.TP
.B M
モノラル
.TP
.B S
ステレオ
.TP
.B s
符合付き整数
.TP
.B u
符合無し整数
.TP
.B x
バイト反転
.PP
一部のモードでは、指定しても効果がないオプションがあります。
たとえば、バイト反転した RIFF WAVE ファイルを作ることは出来ませんし、
U\-Law 出力は Linux PCM デバイスに対しては使用出来ません。
.RE


.TP
.BI \-o " filename"
出力ファイル名を指定します。
出力先がファイルでない場合はこのオプションは無視されます。
\fIfilename\fP を "\-" にすると標準出力に出力されます。

.TP
.BI \-P " filename"
全ての楽器を \fIfilename\fP(パッチ) を用いて演奏します。

.TP
.BI \-p " voices"
最大同時発音数を \fIvoices\fP にします。

.TP
.BI \-Q " channel"
\fIchannel\fP チャネル目を演奏しないようにします。
\fIchannel\fP に負の値を与えると、\-\fIchannl\fP を演奏するようにします。
\fIchannel\fP に \fB0\fP を与えると、全てのチャネルが演奏されます。

.TP
.BI \-R " n"
エンベロープリリースを修正して音響効果を得ます（疑似リバーブ）。
\fIn\fP には以下の値が指定可能です。: 
.RS
.TP
.B 0
Long slight release
.TP
.B 1
Long loud release
.TP
.B 2
Short release
.TP
.B 3
No release
.RE

.TP
.BI \-r
このオプションを有効にすると、リバーブ効果が得られます。

.TP
.BI \-S " size"
リサンプリングキャッシュの大きさをバイト数で指定します。
頻繁に用いられるサンプルは予めリサンプリングしておくことで
高速化しています。ただし、ビブラートやピッチベンドなどによってピッチが
変化するサンプルはキャッシュされません。\fB0\fP を指定すると全くキャッシュ
しません。デフォルトでは \fIsize\fP=\fB2097152\fP (2MB) となっています。

.TP
.BI -s " frequency"
再生サンプルレート (\fBHz\fP または \fBkHz\fP)を指定します。

.TP
.BI -t " code"
日本語テキストの出力文字コードを指定します。
以下の \fIcode\fP が指定可能です(大文字小文字は区別されません)。
.RS
.TP
.B auto
\fILANG\fP 環境変数によって、コードが決まります。
.TP
.B ascii
非可読 ASCII を ピリオド(0x2e) に変換して出力します。
.TP
.B nocnv
出力文字コードを変換しません。
.TP
.B euc
EUC コード(japan) で出力します。
.TP
.B jis
JIS コードで出力します。
.TP
.B sjis
SJIS コードで出力します。
.RE

.TP
.B \-U
このオプションを有効にすると、演奏ごとに毎回、
パッチに割り当てられていたメモリを解放します。

.TP
.BI \-w " mode"
Windows 用の拡張モードのオプションです。
以下の \fImode\fP が有効です。
.RS
.TP
.BI \-w "r"
\fIrcpcv.dll\fP を使用します。
.TP
.BI \-w "R"
\fIrcpcv.dll\fP を使用しません(デフォルト)。
.RE

.TP
.BI \-W "mode"
入力ファイルの拡張子を .WRD または .wrd に変更したファイルが存在すれば、
それを WRDファイル として読み込み、そのコマンドと歌詞を表示します。
.br
表示方法は以下の通り:
.RS
.TP
.BI x
X Window System を使用して、グラフィカルに WRD を表示します。
.TP
.BI t
Escape sequence を使用して、WRD に含まれる文字情報を表示します。
.TP
.BI d
WRD のイベント情報をそのまま出力します。
(dumb WRD tracer)。
.TP
.BI \-
WRD のトレースを行いません。
.RE
なお、WRD は trace モードで実行しないとタイミングが合いません。

.TP
.BI \-WR[opts]
WRD 読み込み時の設定を行います。
.RS
.TP
.B a1=b1,a2=b2,...
WRD 読み込み時のオプションを指定します。an にオプション名、bn にその値が
入ります。
.TP
.B d=n
@WAIT, @WMODE まわりの MIMPI のタイミングに関するバグをエミュレートします。
以下のオプションでエミュレートレベルを変更できます。 
.RS
.TP
.B -WRd=0
MIMPI のバグをエミュレートしないで、規格通りに動作 します。
.TP
.B -WRd=1
(default) 恐らく間違いないと思われるバグのみを エミュレートします。
.TP
.B -WRd=2
怪しいバグまでエミュレートします。 
.RE
エミュレートレベルをあげると、今までタイミングが合っていたものがずれる
可能性があります。
.TP
.BI F=filename
WRD ファイル名を指定します。WRD ファイルが見つからない場合のみ、 指定した filename が WRD ファイルとして用いられます。
.TP
.BI f=filename
WRD ファイル名を指定します。常に指定した WRD ファイル filename を用います。 
.RE

.TP
.BI \-x " str"
指定した文字列で timidity の設定を行います。str の書式は timidity.cfg と同じです。例えば
.br
\fB\-x'bank 0\\n0 violin.pat'\fP
.br
とすると 0 番で指定される音色ををバイオリンにすることができます。
\fI-x\fPに続く文字列中の\fB\\\fP(ASCII 0x5c)は特別文字として扱われ、
それ以降の文字（列）に対しC言語のリテラルと同様の展開が行われます。
例えば、\fB\\n\fPは改行を意味します。


.P
.SH SEE ALSO
lsmidiprog(1), mididump(1), patinfo(1), sf2text(1), wav2pat(1), timidity.cfg(5)


.P
.SH COPYRIGHT
Copyright (C) 1999 Masanao Izumo <mo@goice.co.jp>
Copyright (C) 1995 Tuukka Toivonen <tt@cgs.fi>
.P
Original version was developed under the name of Tuukka Toivonen
<tt@cgs.fi> until the version of TiMidity-0.2i. His development was
discontinued because of his busy work.
.P
This program is free software; you can redistribute it and/or modify
it under the terms of the \fIGNU General Public License\fP as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
.P
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the \fIGNU
General Public License\fP for more details.
.P
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


.SH AVAILABILITY

TiMidity++ は 改良版 TiMidity のページ
.br
URL http://www.goice.co.jp/member/mo/timidity/
.br
で手に入ります。

.SH BUGS
8\-bit と低レートでの出力が思ったより良くない。
.P
小さな CPU\-time\-eating 獣よりも CPU time を喰う。
.P
[訳注：和訳のバグも多数潜んでいるでしょう…]

.P
.SH AUTHORS
\fBVersion 0.2i and earlier:\fP
.br
Tuukka Toivonen <toivonen@clinet.fi>
.br
Vincent Pagel <pagel@loria.fr>
.br
Takashi Iwai <iwai@dragon.mm.t.u-tokyo.ac.jp>
.br
Davide Moretti <dmoretti@iper.net>
.br
Chi Ming HUNG <cmhung@insti.physics.sunysb.edu>
.br
Riccardo Facchetti <riccardo@cdc8g5.cdc.polimi.it>
.br

\fBTiMidity++:\fP
.br
出雲正尚 (IZUMO Masanao) <mo@goice.co.jp>
.br
原田智和 (HARADA Tomokazu) <harada@prince.pe.u-tokyo.ac.jp>
.br
山手圭一郎 (YAMATE Keiichirou) <keiich-y@is.aist-nara.ac.jp>
.br
木竜雅樹 (KIRYU Masaki) <mkiryu@usa.net>
.br
青木大輔 (AOKI Daisuke) <dai@y7.net>
.br
松本庄司 (MATSUMOTO Shoji) <shom@i.h.kyoto-u.ac.jp>
.br
小柳雅明 (KOYANAGI Masaaki) <koyanagi@okilab.oki.co.jp>
.br
今井邦彦 (IMAI Kunihiko) <imai@leo.ec.t.kanazawa-u.ac.jp>
.br
野上貴哉 (NOGAMI Takaya) <t-nogami@happy.email.ne.jp>
.br
渡辺尊紀 (WATANABE Takanori) <takawata@shidahara1.planet.kobe-u.ac.jp>
.br
竹川視野 (TAKEKAWA Hiroshi) <sian@big.or.jp>
.br
長野大介 (NAGANO Daisuke) <breeze.geo@geocities.co.jp> 
.br
山幡為佐久 (YAMAHATA Isaku) <yamahata@kusm.kyoto-u.ac.jp>
.br
木下浩介 (KINOSHITA Kosuke) <kino@krhm.jvc-victor.co.jp>
.br
荒井良重 (ARAI Yoshishige) <ryo2@on.rim.or.jp>
.br
Glenn Trigg <ggt@netspace.net.au>
.br

（敬称略・順不同）。
.P
これ以外にも、TiMidity メーリングリストの皆様をはじめ多くの方から情報、
バグ報告などを頂いています。


.br
WRDで使用される端末ターミナルエミュレーションのコードは X Consotium
等の kterm のコードの一部を取り込み、またそれを参考に実装を行いました。
.br

.br
[和訳は松本庄司(MATSUMOTO Shoji <shom@i.h.kyoto-u.ac.jp>)。
この和訳は正確かどうかは保証できません。
あなたがこの和訳の使用でいかなる損害を受けても責任は持ちません。]

.br
[ TiMidity++ のオプション、cfgファイルの解説は出雲正尚
(IZUMO Masanao <mo@goice.co.jp>)が、
.br
そのnroff化、およびマニュアルのリライトは長野大介
(NAGANO Daisuke <nagano@i.kyushu-u.ac.jp>)が行いました。]
